# Generated by Django 5.0.6 on 2024-06-29 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0002_label_created_at_label_name_alter_label_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='label',
            table=None,
        ),
    ]
