# Generated by Django 5.0.6 on 2024-06-29 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_created_at_task_creator_task_description_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='task',
            table=None,
        ),
    ]
