# Generated by Django 5.0.6 on 2024-06-29 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='status',
            table=None,
        ),
    ]
